### ISSUE TITLE
Markdown Broken with Latest AnchorCMS Update

### ISSUE THREAD

**Issue by tormaid** [danoxide/Snowly#8]
After upgrading to AnchorCMS 0.12.3, markdown translation has stopped working. My posts just display the markdown text and nothing is rendered correctly. Example: http://encodan.info/posts/workstation-iii

Edit: I tested using a fresh copy of your latest build of Snowly and had the same problem. Markdown /does/ work with the latest "default" theme. 

Edit 2: This can be fixed by changing article_markdown to article_html in both posts.php and article.php. I guess the devs changed their minds on that one again ^^;

Edit 3: The above fix breaks the `<!--more-->` tag, which is a bummer. If you know an easy fix to this, that would be really nice. I'm not great with PHP.

**Comment by danoxide** [comment]
Okay, markdown fixed. I didn't add `<!--more-->` tag support, because of CSS styles (first `<p>` element always is bolded). If you want to cut your article text you have to replace `article_html()` to this:
```php
<?php
$contents = explode('<!--more-->', article_html());
echo array_shift($contents);
?>```
